services:
  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '${PHPADMIN_PORT:-8888}:80'
    networks:
      - selenoid

  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    ports:
      - '3306:3306'
    networks:
      - selenoid
    volumes:
      - mariadb_data:/bitnami/mariadb

  opencart:
    image: bitnami/opencart:4.0.2-3-debian-12-r33
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - '${OPENCART_PORT:-8081}:8080'
      - '8443:8443'
    environment:
      - OPENCART_HOST=opencart:8080
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mariadb
    networks:
      - selenoid

  selenoid1:
    image: aerokube/selenoid:latest-release
    command: 
      - "-limit"
      - "10" 
      - "-container-network"
      - "selenoid"
      - "-timeout"
      - "2m"
      - "-service-startup-timeout"
      - "2m"
    volumes:
      - /var/jenkins_home/workspace/Job_Opencart_test/configs/browsers.json:/etc/selenoid/browsers.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "4444"
    networks:
      - selenoid

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    ports:
      - "8083:8080"
    environment:
      - SELENOID_URI=http://selenoid1:4444
    depends_on:
      - selenoid1
    networks:
      - selenoid
      
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      opencart:
        condition: service_healthy
      selenoid-ui:
        condition: service_started
      phpadmin:
        condition: service_started
    entrypoint: ["sh", "-c", "while ! nc -z opencart 8080; do sleep 1; done; exec $$@", "--"]
    command: ["pytest", "-v", "--host=mariadb", "--url=http://opencart:8080", "--alluredir=allure-results", "--executor=selenoid1"]
    networks:
      - selenoid

volumes:
  mariadb_data:
    driver: local

networks:
  selenoid:
    name: selenoid