services:
  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '${PHPADMIN_PORT:-8888}:80'
    networks:
      - selenoid

  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    ports:
      - '3306:3306'
    networks:
      - selenoid
    volumes:
      - mariadb_data:/bitnami/mariadb

  opencart:
    image: bitnami/opencart:4.0.2-3-debian-12-r33
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - '${OPENCART_PORT:-8081}:8080'
      - '8443:8443'
    environment:
      - OPENCART_HOST=opencart:8080  
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      - mariadb
    networks:
      - selenoid

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      opencart:
        condition: service_healthy
    entrypoint: ["sh", "-c", "while ! nc -z opencart 8080; do sleep 1; done; exec $$@", "--"]
    command: ["pytest", "-v", "--host=mariadb", "--url=http://opencart:8080", "--alluredir=allure-results", "--headless", "--browser=br", "--container"]
    networks:
      - selenoid

volumes:
  mariadb_data:
    driver: local

networks:
  selenoid:
    external: true
    name: selenoid